import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ProviderAuth from '@/app/components/ProviderAuth';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Super App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderAuth>
          {children}
        </ProviderAuth>
      </body>
    </html>
  );
}
